### ISSUE TITLE
Replace static config variable injection with a deeper integration with Zookeeper

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/mesos-ui#2]
At the moment the master URL for mesos is injected as an environment variable at runtime to the node process. This could be problematic for example if the master changes during flight and we cannot retrieve the API data correctly.

We could integrate deeper with zookeeper perhaps using something like https://github.com/yfinkelstein/node-zookeeper and retrieve the leading master URL via that.

**Comment by ankurcha** [comment]
+1

**Comment by protochron** [comment]
+1. If you're running a HA Mesos cluster with multiple masters and an election happens then the Mesos-UI data gets stale and you need to restart the whole thing.

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/mesos-ui/commit/aecc56795b1bdbb13eadd14fe725b0bba6166758
