### ISSUE TITLE
Running this on a large mesos cluster causes the cluster to lock up

### ISSUE THREAD

**Issue by steveniemitz** [Capgemini/mesos-ui#43]
I just tested this on a large-ish (250+ slaves, ~2,000 active tasks) cluster, and running it caused the cluster to lock up.  (Also the UI didn't really work at all)

My guess is this requests /state.json a lot on the master, which essentially blocks all operations on the master until the request completes.

**Comment by wallies** [comment]
@steveniemitz in src/config/config.js we set an update interval of 5000ms, which is how often the api will call out to the /state.json. This might be a bit too often for a very large cluster. We have only tested with a very small cluster. I also intend to do work on this for the MesoCon Europe Hackathon to make work with 0.24 and 0.25.

**Comment by jolexa** [comment]
This might be solved with mesos-0.27.0 per https://issues.apache.org/jira/browse/MESOS-2353
