### ISSUE TITLE
Investigate removing serverside nodejs dependency

### ISSUE THREAD

**Issue by enxebre** [Capgemini/mesos-ui#44]
To explore and consider removing the dependency with the server side running on nodejs so integration/deployment/bootstrap with mesos core becomes easy.

**Comment by tayzlor** [comment]
Things we'd need to consider - 

- static files that are served
- moving all the socket.io + Mesos API integration code into the frontend

**Comment by enxebre** [comment]
:+1:

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini/mesos-ui/commit/6399ea190af1c8ee9842303ff4d140ebc87b64af
