### ISSUE TITLE
Embed/Include external dependencies

### ISSUE THREAD

**Issue by mindscratch** [Capgemini/mesos-ui#45]
I'd like to try mesos-ui, however, I'd be running it on a server that doesn't have access to the internet. Looking at just the index.html, that means some fonts and js wouldn't load.

It would be great if the resources were embedded or included with the release to avoid having to talk to external servers.

**Comment by wallies** [comment]
@mindscratch we have raised this #44 to remove the server side dependency so we can look to include it as an alternate mesos-ui when you run up mesos. We will look to remove external font and js dependencies when we are doing this.
