### ISSUE TITLE
Allow the application to run on a URL path other than /

### ISSUE THREAD

**Issue by ndeslandes** [Capgemini/mesos-ui#46]
When you deploy this app on a mesos cluster with docker on random port, it's  usefull to use a tool like consul-template to configure a ngnix to proxy the call behind a path like /mesos-ui/. Right now the application does not allow it

**Comment by enxebre** [comment]
We have depcreated standalone mode for the sake of a deeper easy integration with mesos so this should not be a problem now.
Thanks!
