### ISSUE TITLE
UI only ?

### ISSUE THREAD

**Issue by scalp42** [Capgemini/mesos-ui#65]
Is there a way to run the UI only ?

Meaning a container that does not extend the mesos one (or participate as master/slave)?

I also can't find the tag `stand-alone` per README.

Any ideas?

Thanks in advance!

**Comment by scalp42** [comment]
When trying to run the UI:

```
docker run -dti -p 5000:5000 -p 8000:8000 -e MESOS_ENDPOINT=http://10.52.41.115:5050 --name ui capgemini/mesos-ui:0.1.1
```
I'm getting the following page:

![](https://i.imgur.com/qnXRSch.png)

**Comment by enxebre** [comment]
Hi @scalp42,
yes there's a way, that's what the standalone approach is for, we just hadn't build the image yet on dockerhub, we are rebuilding it now so you should be able to download it in the next minutes via ```capgemini/mesos-ui:standalone-0.1.2```

Regarding your second, that is expected as explained here https://github.com/Capgemini/mesos-ui/tree/0.1.1#running-the-docker-container
That's just the stub server, you can stop it by setting environment variable ```NODE_ENV=production``` the app should be running on 5000.

Cheers

**Comment by enxebre** [comment]
https://hub.docker.com/r/capgemini/mesos-ui/tags/
