### ISSUE TITLE
Running image capgemini/mesos-ui:stand-alone results in "Tag stand-alone not found in repository docker.io/capgemini/mesos-ui"

### ISSUE THREAD

**Issue by akunaatrium** [Capgemini/mesos-ui#69]
Copy-pasted the following from the main readme:
```
docker run -p 5000:5000 -e MESOS_ENDPOINT=http://master.mesos:5050 capgemini/mesos-ui:stand-alone
```
Got the response:

Unable to find image 'capgemini/mesos-ui:stand-alone' locally
Pulling repository docker.io/capgemini/mesos-ui
Tag stand-alone not found in repository docker.io/capgemini/mesos-ui

**Comment by wallies** [comment]
cheers for spotting this. it appears we tagged it as standalone-0.1.2. Will update documentation now.

**Comment by akunaatrium** [comment]
I can see the update in readme which says the image to run is
```
capgemini/mesos-ui:standalone-$TAG
```
without an explanation of what a $TAG is, where to get the value or how to define it. One familiar with Docker could possibly assume that the $TAG represents Docker image tag, goes to Docker Hub and finds a list of tags, one of them as "standalone-0.1.2". Replaces the $TAG with "standalone-0.1.2" and receives an error because there is no such tag as "standalone-standalone-0.1.2".

Am I making any sense?

**Comment by enxebre** [comment]
hey @akunaatrium thanks for feedback, please feel free to create a PR for improving the readme in any way. Every feeback from someone neutral (i.e people who does not wrote the code ) is very welcome :)

**Comment by wallies** [comment]
hey @akunaatrium very good point. By tag i meant github repo tag. I will update the readme to make it clearer
