### ISSUE TITLE
MESOS_ENDPOINT in case of HA mesos cluster

### ISSUE THREAD

**Issue by geoffroyjabouley** [Capgemini/mesos-ui#82]
Hello
your work is very promising!
I was just testing the mesos-ui today, and i get stuck at the point of providing the MESOS_ENDOINT variable.
We have a HA mesos cluster, with 3 Mesos masters.

I tried providing the mesos leader as MESOS_ENDPOINT, it works fine.

I also tried providing a mesos follower as MESOS_ENDPOINT, and it seems redirection to the leader is not working. UI keep refreshing with a "This master is not the leader, redirecting..." message, but nothing shows up.
Can i activate some debug logs for investigation?

Anyway, what about supporting  zookeeper urls (zk://mesos1:2181,mesos2:2181,mesos:2181/mesos) as the endpoint, so the UI can always talk to the leader?

**Comment by enxebre** [comment]
Hi @geoffroyjabouley thanks for pointing out this!
The zookeeper component was designed without the standalone mode in mind so it assumes it's running as the default UI for mesos.
https://github.com/Capgemini/mesos-ui/blob/master/src/components/ZookeeperRedirect/ZookeeperRedirect.js#L23

So It's a bug, yeah ideally we should manage to get the leader all the time.

**Comment by geoffroyjabouley** [comment]
Thanks
i've read that you plan to deprecate the standalone mode.
Too bad, i was trying it so i could display on an external display on the wall of our openspace a global/readable status of our mesos cluster (especially the Dashboard and Nodes panels)

**Comment by wallies** [comment]
@geoffroyjabouley we plan to keep support for the standalone and default mode. Our old standalone mode used a NodeJS API and called out to the Mesos API via the API. Now the standalone mode is basically just there to serve the static files.

**Comment by enxebre** [comment]
https://github.com/Capgemini/mesos-ui/pull/83

**Comment by enxebre** [comment]
@geoffroyjabouley Fixed by #83

**Comment by geoffroyjabouley** [comment]
:+1:
