### ISSUE TITLE
ZOOKEEPER_ADDRESS should accept domain names too

### ISSUE THREAD

**Issue by jeacott1** [Capgemini/mesos-ui#94]
just wasted ages trying to figure out why this wouldn't start.
this works:
```
ZOOKEEPER_ADDRESS="ip1:2181,ip2:2181,ip3:2181"
```
this doesn't, but should!
```
ZOOKEEPER_ADDRESS="some_domain_that_resolves_to_an_ip:2181"
```

**Comment by rhoml** [comment]
This is accepted at the moment. 
We are running it using our Consul DNS for zookeeper 
`ZOOKEEPER_ADDRESS=prod.zookeeper.service.xxxx.consul:2181`

**Comment by enxebre** [comment]
yep, It will resolve whatever is resolvable and will reach whatever is reachable from inside the container.
@rhoml it'd be nice if you can create a PR adding the name of your company to the list in the readme
thanks!

**Comment by rhoml** [comment]
So I think that this issue can be closed
