### ISSUE TITLE
Unable to access UI

### ISSUE THREAD

**Issue by mindscratch** [Capgemini/mesos-ui#96]
I'm running Mesos 0.28.2 and I just started the standalone-0.1.4 image with:
`docker run -p 33000:33000 -e MESOS_ENDPOINT=http://master.mesos:5050 capgemini/mesos-ui:standalone-0.1.4`

The output of the container shows some "Starting messages" and the last message says "Finied 'server' after 1.35s".

I try to curl localhost:33000 and also try to browse to my_server:33000 and I get nothing. When I curl, I get `curl: (56) Recv failure: Connection reset by peer`.

Any thoughts/ideas? I notice the README in the gihtub repo instructions is different than on [docker hub](https://hub.docker.com/r/capgemini/mesos-ui/), not sure which is correct. Also, on docker hub I just noticed it is compatible with mesos 0.23....is that accurate?

**Comment by enxebre** [comment]
Hi,
the output message is expected but the server is listening on 5000 https://github.com/Capgemini/mesos-ui/blob/master/src/config/config.js#L4 inside the container so ```docker run -p 33000:33000``` is never going to give you access to the server. Instead you should docker run -p 33000:5000, then try to curl  localhost:33000
Thanks!

**Comment by mindscratch** [comment]
Yup, my mistake, thanks.
